sudo: false
# Travis actually needs to have python, ruby, and nodejs installed.
# It _seems_ virtualenv is only available when the language is set to python
# When language=python it seems Travis runs this command:
# source ~/virtualenv/python2.7/bin/activate
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      # - xsltproc libxml2-utils

# Cache the 3rd-party packages. From https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - nvm install $(< ./.nvmrc)
  - rvm default
install: ./script/setup
script: ./script/ci
after_success:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
